### ISSUE TITLE
Bug: Invalid postal code format

### ISSUE THREAD

**Issue by rimgik** [AY2425S1-CS2103T-T13-2/tp#111]
It's stated that a postal code must be 6 digits, but when using the command `find` to find customer by postal code, it doesn't check if the postal code given is indeed 6 digits.

 Example: `find S123`

**Comment by yyanyee** [comment]
Will add in the user guide that users can search using part of the postal code eg `find S560`. I think this will be useful for searching by area. For example, postal codes starting with 560 is the area code for Ang Mo Kio
