### ISSUE TITLE
Bug: Ambiguity in the `find` command

### ISSUE THREAD

**Issue by rimgik** [AY2425S1-CS2103T-T13-2/tp#113]
It was mentioned that to find a customer by postal code, we can use `find <postal code>`, and to find a customer by phone number, we can use `find <phone number>`.

However, this creates ambiguity, as it’s unclear whether the command find `123456` is searching for a customer with the postal code `123456` or a customer with a phone number containing `123456`.

Suggestion: To find a customer by postal code, always prefix the postal code with `S`.

**Comment by yyanyee** [comment]
bug fixed in pr #133
