### ISSUE TITLE
Bug: Mismatch between user guide and feature

### ISSUE THREAD

**Issue by rimgik** [AY2425S1-CS2103T-T13-2/tp#114]
It was mentioned in the release note that:
- `edit 1 t/vg` adds a tag with the name Vegetarian

But testing revealed that running `edit 1 t/vg` will also remove other tag that is not labeled as `Vegetarian`

**Comment by noth-k** [comment]
This is not a bug, it is how the original edit command works where the new tags with the edit command would replace the previous tags. The release notes will be updated. Thanks
