### ISSUE TITLE
Bug: Add command not working properly

### ISSUE THREAD

**Issue by rimgik** [AY2425S1-CS2103T-T13-2/tp#115]
It was mentioned in the release notes that we can quickly add a customer with tags by running:
- `add n/Alex Russo t/v`

However, testing indicates that this command does not appear to be working.
<img width="737" alt="image" src="https://github.com/user-attachments/assets/089108e4-2b1c-4350-b110-4473ad9e5537">

**Comment by noth-k** [comment]
The shortcut functionality works in conjunction with the add functionality. As such, the necessary parameters for the add command will still be needed. Will update the release notes for clarity. Thanks
