### ISSUE TITLE
Bug: History Command Fails to Recognise Capitalisation Variations in Customer Names

### ISSUE THREAD

**Issue by noth-k** [AY2425S1-CS2103T-T13-2/tp#116]
input entered: `history john doe`

output encountered: `Person does not exist: john doe`

<img width="844" alt="image" src="https://github.com/user-attachments/assets/7e15cfe6-3bf0-4d97-9087-e404ff4a3a4c">

**Comment by rimgik** [comment]
This is not a bug, as of right now it's possible to add a customer with the same name but with different capitalisation, we need to able to differentiate between them.

**Comment by rimgik** [comment]
This is not a bug, as of right now it's possible to add a customer with the same name but with different capitalisation, we need to able to differentiate between them.
