### ISSUE TITLE
Bug: Tagging conflicts for same shortcut

### ISSUE THREAD

**Issue by yyanyee** [AY2425S1-CS2103T-T13-2/tp#126]
The same shortcut can be given to the same tag, instead of flagging out to user that shortcut already exists. 
For example `addShortCut al/v tn/Vegan` and `addShortCut al/ve tn/Vegan` will both create a shortcut for the tag `Vegan`

**Comment by noth-k** [comment]
If I am not wrong, there is an issue already opened for this problem.
