### ISSUE TITLE
Bug: Filter for shortcut tags

### ISSUE THREAD

**Issue by yyanyee** [AY2425S1-CS2103T-T13-2/tp#128]
Filter command will only work for shortcut tags if full name is typed out. 

For example , (assuming `v` is shortcut for `vegan` and `vg` is shortcut for `vegetarian`), `filter v` will not show all with `Vegetarian` and `vegan` tag but `filter fri` will show all with `friends tag`

**Comment by noth-k** [comment]
Thanks. Will be addressed in v1.5
