### ISSUE TITLE
Bug: DelShortCut not case insensitive

### ISSUE THREAD

**Issue by yyanyee** [AY2425S1-CS2103T-T13-2/tp#129]
Assuming there exists a shortcut `v` for `Vegan`, `delShortCut al/v tn/Vegan` will delete shortcut `v` but `delShortCut al/v tn/vegan` will run into error. 

Else, can update UserGuide to say that `DelShortCut` is case sensitive

**Comment by noth-k** [comment]
Thanks. Will be updated in v1.5
