### ISSUE TITLE
[PE-D][Tester D] Case sensitivity in name for assigning order to customer

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-2/tp#212]
Step1: `put tomato n/bernice yu`

![image.png](https://raw.githubusercontent.com/miuna9890/ped/main/files/ae51fbda-2bce-43a4-a237-a4336f933fac.png)

Severity: Medium

Justification: as person names are not case sensitive in the real world, they shouldn't be
 case sensitive in the app either. It would be confusing for the user to use the app when names are case sensitive for the order feature but not when adding or finding by name. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: miuna9890/ped#11

**Comment by rimgik** [comment]
Not a bug: Right now we allow customer with the same name but different case sensitivity in the application
