### ISSUE TITLE
[PE-D][Tester D] UG command format has missing commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T13-2/tp#227]
![image.png](https://raw.githubusercontent.com/miuna9890/ped/main/files/8d40d505-94c4-431b-b8ef-1ef23f5f6a34.png)

Justification: 
UG command format has missing commands such as archive, unarchive, order, deleteOrder, put order, listOrder

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: miuna9890/ped#19

**Comment by rimgik** [comment]
Duplicate with #171
