### ISSUE TITLE
[PE-D][Tester E] DG: Model UML Class diagram missing composition

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-2/tp#230]
AddressBook class contains a UniqueOrderList:
![image.png](https://raw.githubusercontent.com/sannie-beep/ped/main/files/38560396-83eb-4420-9ad1-77863494f0f5.png)

But no composition arrow is drawn from AddressBook -> UniqueOrderList
![image.png](https://raw.githubusercontent.com/sannie-beep/ped/main/files/b9b8e01b-055b-420e-aa1d-bb1244098391.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: sannie-beep/ped#14

**Comment by rimgik** [comment]
Duplicate with #198
